//! A checked C export drives native entry adapters and both interface views.
use crate::op::{FnSig, Ty};
use std::rc::Rc;

pub(crate) struct Export {
    pub function: String,
    pub name: String,
    pub symbol: String,
    pub signature: Rc<FnSig>,
    pub documentation: String,
}

pub(crate) fn check_signature(
    inputs: &[(String, Ty)],
    output: &Option<Ty>,
) -> Result<(), &'static str> {
    if inputs
        .iter()
        .any(|(_, ty)| !ty.is_numeric() && !matches!(ty, Ty::Ref(inner, _) if inner.is_numeric()))
        || output.as_ref().is_some_and(|ty| {
            !ty.is_numeric()
                && !result_payloads(ty).is_some_and(|(ok, error)| {
                    (*ok == Ty::Unit || ok.is_numeric()) && error.is_numeric()
                })
        })
    {
        return Err("C exports currently require numeric scalar parameters or scalar borrows, and a numeric scalar, (), or Result[scalar or (), scalar] return");
    }
    Ok(())
}

pub(crate) fn result_payloads(ty: &Ty) -> Option<(&Ty, &Ty)> {
    match ty {
        Ty::Enum(t) if t.propagatable() && !t.is_option() => {
            Some((&t.variants[0].fields[0], &t.variants[1].fields[0]))
        }
        _ => None,
    }
}

pub(crate) fn c_type(ty: &Ty) -> String {
    if let Ty::Ref(inner, mutable) = ty {
        return format!(
            "{}{} *",
            if *mutable { "" } else { "const " },
            c_type(inner)
        );
    }
    match ty {
        Ty::I8 => "int8_t",
        Ty::I16 => "int16_t",
        Ty::I32 => "int32_t",
        Ty::I64 => "int64_t",
        Ty::U8 => "uint8_t",
        Ty::U16 => "uint16_t",
        Ty::U32 => "uint32_t",
        Ty::U64 => "uint64_t",
        Ty::F32 => "float",
        Ty::F64 => "double",
        _ => unreachable!("checked C export type"),
    }
    .into()
}

/// The namespace is also an importable Plenty module name and a C identifier.
pub(crate) fn check_library_name(name: &str) -> Result<(), Box<dyn std::error::Error>> {
    if name.is_empty()
        || !name.as_bytes()[0].is_ascii_alphabetic()
        || !name.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'_')
        || crate::frontend::builtin(name)
        || crate::frontend::reserved(name)
    {
        return Err(
            "library name must be a non-builtin ASCII identifier beginning with a letter".into(),
        );
    }
    Ok(())
}

pub(crate) struct Interface {
    pub name: String,
    pub discovery: String,
    pub source: String,
    pub header: String,
}

impl Interface {
    pub fn new(name: &str, exports: &[Export]) -> Result<Self, Box<dyn std::error::Error>> {
        check_library_name(name)?;
        if exports.is_empty() {
            return Err("library requires at least one `export def` declaration".into());
        }
        let discovery = format!("{name}_plenty_interface_v1");
        let prefix = format!("{name}_");
        for export in exports {
            if !export.symbol.starts_with(&prefix) || export.symbol == discovery {
                return Err(format!("C export `{}` must start with `{prefix}` and cannot use reserved discovery symbol `{discovery}`", export.symbol).into());
            }
        }
        let mut source = format!("# plenty-interface-format: 1\n# library: {name}\n# target: {}\n# abi: C\n# This file is generated; its exact UTF-8 bytes are embedded in the library.\n# Linking remains explicit. Calls may terminate the process on runtime traps.\n\n", crate::native_target());
        // Preserve case: two case-distinct library namespaces need distinct guards.
        let guard = format!("PLENTY_HEADER_{name}_V1");
        let mut header = format!("/* Generated by Plenty. Target: {}. C ABI contract format 1. */\n#ifndef {guard}\n#define {guard}\n#include <stdint.h>\n#include <stddef.h>\n#ifdef __cplusplus\nextern \"C\" {{\n#endif\n\n/* All calls must be serialized on the same caller thread.\n * Foreign dependencies must honor their declared contracts.\n * Runtime traps and unchecked allocation failures terminate the process;\n * no exception or nonlocal jump may cross a Plenty frame.\n * Keep the originating shared library loaded while calling its functions.\n */\n", crate::native_target());
        for export in exports {
            let result = export.signature.outputs.first().and_then(result_payloads);
            header.push_str("\n/* Plenty declaration: ");
            header.push_str(&export.name);
            header.push_str(".\n * Guarantees: scalar values are copied; no ownership crosses this interface.\n * Borrowed storage is never retained after this call.\n");
            for (i, (_, ty)) in export.signature.inputs.iter().enumerate() {
                if let Ty::Ref(inner, mutable) = ty {
                    header.push_str(&format!(" * Requires p{i}: non-null, aligned, initialized {} storage, valid\n * for this whole call (one element, sizeof({}) bytes).\n", c_type(inner), c_type(inner)));
                    if *mutable {
                        header.push_str(&format!(" * p{i} is borrowed exclusively: storage must be readable and writable,\n * must not overlap any other borrowed argument, and no other alias may\n * access it during the call (including concurrent or reentrant access).\n * On every normal return, the final value is written back to p{i}.\n"));
                    } else {
                        header.push_str(&format!(" * p{i} is borrowed read-only: storage must be readable and must not\n * be mutated through any alias during the call. Shared reads may alias.\n * This call leaves p{i}'s storage unchanged.\n"));
                    }
                }
            }
            if !export.documentation.is_empty() {
                header
                    .push_str(" * Author documentation (additional to the generated contract):\n");
                for line in export.documentation.lines() {
                    // Do not let author text close a comment or splice C source lines.
                    header.push_str(&format!(
                        " * {}\n",
                        line.replace("*/", "* /")
                            .replace('\\', "\\ ")
                            .replace('?', "? ")
                    ));
                }
            }
            header.push_str(" */\n");
            let output = export
                .signature
                .outputs
                .first()
                .filter(|_| result.is_none())
                .map(c_type)
                .unwrap_or_else(|| "void".into());
            let mut parameters: Vec<_> = export
                .signature
                .inputs
                .iter()
                .enumerate()
                .map(|(i, (_, ty))| format!("{} p{i}", c_type(ty)))
                .collect();
            if let Some((ok, error)) = result {
                header.push_str("/* Returns 0 for Ok, 1 for Err; no other status is returned.\n * Output pointers must be non-null, aligned, writable, mutually disjoint,\n * and disjoint from all input borrows for the whole call.\n * Output storage need not be initialized. Only the selected output is written;\n * the other output is unchanged. No old output value is released.\n * Err does not promise to undo mutations to borrowed inputs.\n */\n");
                if *ok != Ty::Unit {
                    parameters.push(format!("{} *out_ok", c_type(ok)));
                }
                parameters.push(format!("{} *out_error", c_type(error)));
            }
            header.push_str(&format!(
                "{} {}({});\n",
                if result.is_some() {
                    "uint32_t"
                } else {
                    &output
                },
                export.symbol,
                if parameters.is_empty() {
                    "void".into()
                } else {
                    parameters.join(", ")
                }
            ));
            // Generated names avoid C keyword and Unicode parameter hazards.
            let parameters: Vec<_> = export
                .signature
                .inputs
                .iter()
                .enumerate()
                .map(|(i, (_, ty))| format!("p{i}: {ty}"))
                .collect();
            let output = export
                .signature
                .outputs
                .first()
                .map(ToString::to_string)
                .unwrap_or("()".into());
            if let Some((ok, error)) = result {
                let raw = format!("_plenty_c_{}", export.name);
                if exports.iter().any(|e| e.name == raw) {
                    return Err(
                        format!("export name `{raw}` conflicts with a generated adapter").into(),
                    );
                }
                let mut raw_parameters = parameters.clone();
                let mut args: Vec<_> = (0..parameters.len()).map(|i| format!("p{i}")).collect();
                let mut body = String::new();
                if *ok != Ty::Unit {
                    raw_parameters.push(format!("out_ok: &mut {ok}"));
                    args.push("&mut out_ok".into());
                    body.push_str(&format!("    mut out_ok: {ok} = 0\n"));
                }
                raw_parameters.push(format!("out_error: &mut {error}"));
                args.push("&mut out_error".into());
                body.push_str(&format!("    mut out_error: {error} = 0\n    status = {raw}({})\n    if status == 0:\n        Ok({})\n    else:\n        Err(out_error)\n", args.join(", "), if *ok == Ty::Unit { "()" } else { "out_ok" }));
                source.push_str(&format!(
                    "extern def {raw}({}) -> u32 = \"{}\"\npub def {}({}) -> {output}:\n{body}\n",
                    raw_parameters.join(", "),
                    export.symbol,
                    export.name,
                    parameters.join(", ")
                ));
            } else {
                source.push_str(&format!(
                    "pub extern def {}({}) -> {output} = \"{}\"\n",
                    export.name,
                    parameters.join(", "),
                    export.symbol
                ));
            }
        }
        header.push_str(&format!("\n/* Requires: length points to writable, aligned size_t storage (not null).\n * Writes the byte length; returns immutable UTF-8 metadata, without a NUL\n * terminator. Borrowed until library unload; never modify or free it.\n * The call does not allocate or retain length.\n */\nconst uint8_t *{discovery}(size_t *length);\n\n#ifdef __cplusplus\n}}\n#endif\n#endif /* {guard} */\n"));
        Ok(Self {
            name: name.into(),
            discovery,
            source,
            header,
        })
    }
}
